# -*- coding: utf-8 -*-
"""Produccion_Knn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Hh8qrjnw5tcK6V0rq89yryv4uv4MViX
"""

!pip install streamlit

import streamlit as st
import joblib
import pandas as pd

# Cargar el modelo KNN
modelo_knn = joblib.load("modelo_KNN.joblib")  # Asegúrate de que el archivo esté en el mismo directorio

# Título de la aplicación
st.title("Modelo de Producción KNN")
st.write("Ingresa los valores para realizar la predicción.")

# Entrada de datos
feature1 = st.number_input("Feature 1: Precio unitario", min_value=0.0, step=0.1)
feature2 = st.number_input("Feature 2: Cantidad", min_value=0.0, step=0.1)

# Botón para predecir
if st.button("Predecir"):
    try:
        input_data = pd.DataFrame([[feature1, feature2]], columns=["feature1: Precio unitario", "feature2:Cantidad"])
        prediction = modelo_knn.predict(input_data)
        st.success(f"Predicción: {prediction[0]}")
    except Exception as e:
        st.error(f"Error: {e}")